### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jvanstraten** [QE-Lab/dqcsim-qx#1]
- [x] run a basic algorithm (Deutsch-Josza, added as test)
 - [x] fix liblexgram.so dependency in shared object (manylinux wheel script)
 - [ ] add arb parameter parsing
 - [ ] docs
